version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-courses
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbcourses
      - POSTGRES_DB=courses-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
