version: '3.8'

services:

  db:
    image: postgres:13
    container_name: postgres-courses-web
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbcourses
      - POSTGRES_DB=courses-db-web
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: unless-stopped

  backendapi:
    build: ./back-end-api
    container_name: backendapi-courses
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8181:8181"
    depends_on:
      - db
      - rabbitmq
    restart: unless-stopped

  backend:
    build: ./back-end
    container_name: backend-courses
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    depends_on:
      - backendapi
      - db
      - rabbitmq
    restart: unless-stopped

  front-end:
    build: ./front-end
    container_name: frontend-courses
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
  pgdata-api:
